# Generated by Django 6.0.5 on 2026-05-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='is_daily',
            field=models.BooleanField(default=False),
        ),
    ]
