# Generated by Django 6.0.5 on 2026-05-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userscore_is_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='summary_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
