# Generated by Django 6.0.5 on 2026-05-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userscore_summary_data'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userscore',
            index=models.Index(fields=['user', '-created_at'], name='users_users_user_id_1aec84_idx'),
        ),
        migrations.AddIndex(
            model_name='userscore',
            index=models.Index(fields=['user', 'completed', '-created_at'], name='users_users_user_id_ae1db3_idx'),
        ),
        migrations.AddIndex(
            model_name='userscore',
            index=models.Index(fields=['user', 'is_daily', '-created_at'], name='users_users_user_id_af3af8_idx'),
        ),
    ]
