# Generated by Django 6.0.5 on 2026-05-25 09:10

import apps.users.models
import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.avatar_upload_path, validators=[apps.users.validators.validate_avatar]),
        ),
    ]
