# Generated by Django 6.0.5 on 2026-05-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_strict_matching'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='game_mode',
            field=models.CharField(choices=[('complete_lyrics', 'Complete Lyrics'), ('guess_song', 'Guess Song'), ('pick_song', 'Pick Song')], db_index=True, default='complete_lyrics', max_length=20),
        ),
        migrations.AddIndex(
            model_name='userscore',
            index=models.Index(fields=['completed', 'game_mode', '-score', '-created_at'], name='users_users_complet_e3df68_idx'),
        ),
    ]
