# Generated by Django 6.0.5 on 2026-05-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userscore_game_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_notifications',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('insane', 'Insane')], default='medium', max_length=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_rounds',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
