# Generated by Django 6.0.5 on 2026-05-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userprofile_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_last_played_date',
            field=models.DateField(blank=True, db_index=True, help_text='Last calendar date logged.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_streak_current',
            field=models.PositiveIntegerField(default=0, help_text='Continuous active win streak.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_streak_longest',
            field=models.PositiveIntegerField(default=0, help_text='All-time high-water streak record.'),
        ),
    ]
