# Generated by Django 6.0.5 on 2026-05-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_daily_last_played_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='daily_last_played_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='daily_streak_current',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='daily_streak_longest',
        ),
    ]
