# Generated by Django 6.0.5 on 2026-05-29 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_fully_cached', models.BooleanField(default=False, help_text='True if top tracks are locally stored.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('playcount', models.IntegerField(default=0)),
                ('mbid', models.CharField(blank=True, default='', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='lyrics.artist')),
            ],
            options={
                'ordering': ['-playcount'],
                'unique_together': {('artist', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LyricCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(blank=True, default='', max_length=255)),
                ('duration', models.IntegerField(default=0)),
                ('plain_lyrics', models.TextField(blank=True, null=True)),
                ('synced_lyrics', models.TextField(blank=True, null=True)),
                ('instrumental', models.BooleanField(default=False)),
                ('has_no_lyrics', models.BooleanField(default=False, help_text='Flag true if API explicitly yields 404.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lyric_cache', to='lyrics.track')),
            ],
        ),
    ]
