# Generated by Django 6.0.5 on 2026-05-28 20:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lyrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='The specific day this puzzle goes live.', unique=True)),
                ('game_mode', models.CharField(choices=[('complete_lyrics', 'Complete the Lyrics'), ('guess_song', 'Guess Song')], default='complete_lyrics', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('insane', 'Insane')], default='medium', max_length=12)),
                ('lyrics_prompt', models.TextField(help_text='The targeted verse snippet (pre-blanked with ________ if mode demands it).')),
                ('cached_answer', models.CharField(help_text='The pre-vetted, raw expected normalized answer string.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(help_text='The underlying local vended track record.', on_delete=django.db.models.deletion.PROTECT, related_name='daily_challenges', to='lyrics.track')),
            ],
            options={
                'verbose_name': 'Daily Challenge',
                'verbose_name_plural': 'Daily Challenges',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyChallengeLedger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False, help_text='True if the challenge was won.')),
                ('score_achieved', models.PositiveIntegerField(default=0)),
                ('guesses_taken', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('completed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('daily_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='game.dailychallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenge_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Challenge Ledger',
                'verbose_name_plural': 'Daily Challenge Ledgers',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['daily_challenge', '-score_achieved', 'completed_at'], name='game_dailyc_daily_c_a4ca16_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'daily_challenge'), name='unique_user_per_daily_challenge')],
            },
        ),
    ]
