# Generated by Django 6.0.5 on 2026-05-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailychallenge',
            name='track',
        ),
        migrations.RemoveIndex(
            model_name='dailychallengeledger',
            name='game_dailyc_daily_c_a4ca16_idx',
        ),
        migrations.RemoveConstraint(
            model_name='dailychallengeledger',
            name='unique_user_per_daily_challenge',
        ),
        migrations.RemoveField(
            model_name='dailychallengeledger',
            name='daily_challenge',
        ),
        migrations.RemoveField(
            model_name='dailychallengeledger',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyChallenge',
        ),
        migrations.DeleteModel(
            name='DailyChallengeLedger',
        ),
    ]
